name: Build APK

on:
  push:
    branches:
      - main

jobs:
  apk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: |
          uv sync

      - name: Build
        run: |
          uv run flet build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/apk/**/*.apk